---
# tasks file for vmware
- name: Clone a virtual machine from Windows template and customize
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    folder: "{{ vmware_new_vm_folder }}"
    datacenter: "{{ ha_datacenter }}"
    cluster: "{{ vmware_cluster_name }}"
    datastore: "{{ virtual_machine_datastore }}"
    name: "{{ new_vm_name }}"
    template: "{{ template_name }}"
    networks:
    - name: "{{ nic_virt_group }}"
      ip: "{{ nic_ip }}"
      netmask: "{{ nic_netmask }}"
      gateway: "{{ nic_gw }}"
      #mac: aa:bb:dd:aa:00:14
      domain: "{{ win_domain }}"
      dns_servers:
      - "{{ win_dns1 }}"
      - "{{ win_dns2 }}"
    #- vlan: 1234
    #  type: dhcp
    disk:
    - size_gb: 40
      controller_type: 'SCSI'
      controller_number: 0
      unit_number: 0
    customization:
      autologon: yes
      dns_servers:
      - "{{ win_dns1 }}"
      - "{{ win_dns2 }}"
      #domain: "{{ win_domain }}"
      password: "{{ new_vm_password }}"
      domainadmin: "{{ ad_admin }}"
      domainadminpassword: "{{ ad_admin_pass }}"
    wait_for_ip_address: yes
    hardware:
       memory_mb: "{{ RAM }}"
       num_cpus: "{{ CPU }}"
       num_cpu_cores_per_socket: 2
       hotadd_cpu: True
       hotremove_cpu: True
       hotadd_memory: True
  delegate_to: localhost
     
      #runonce:
      #- powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
  #delegate_to: localhost

